# Generated by Django 4.2.30 on 2026-09-16 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("service_app", "0003_providerprofile_customerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="service_app.providerprofile",
            ),
        ),
    ]
